# Ideally github action will ssh into server build and run this docker-compose.prod.yml
# But it might not work so we'll have to manually build and run the image on the server in that case
services:
  app:
    # build:
    #   context: .
    volumes:
      - ./adminList.txt:/app/adminList.txt:ro
      # - ./uploads:/app/uploads
  #   env_file: .env
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - REDIS_URL=${REDIS_URL}

  # postgres:
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  # redis:
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
