import type {
  CalendarDay,
  OnDutyTA,
  RecurringRule,
  ScheduleSession,
  TimeSlot,
} from "./types";

// TODO: Replace dummy schedule data with API data after schema is finalized.
export const CALENDAR_DAYS: CalendarDay[] = [
  { key: "mon", label: "MON", date: "23" },
  { key: "tue", label: "TUE", date: "24" },
  { key: "wed", label: "WED", date: "25" },
  { key: "thu", label: "THU", date: "26" },
  { key: "fri", label: "FRI", date: "27" },
  { key: "sat", label: "SAT", date: "28" },
  { key: "sun", label: "SUN", date: "29" },
];

export const TIME_SLOTS: TimeSlot[] = [
  { label: "09:00 AM", hour: 9 },
  { label: "10:00 AM", hour: 10 },
  { label: "11:00 AM", hour: 11 },
  { label: "12:00 PM", hour: 12 },
  { label: "01:00 PM", hour: 13 },
  { label: "02:00 PM", hour: 14 },
  { label: "03:00 PM", hour: 15 },
  { label: "04:00 PM", hour: 16 },
  { label: "05:00 PM", hour: 17 },
  { label: "06:00 PM", hour: 18 },
];

export const DUMMY_SCHEDULE_SESSIONS: ScheduleSession[] = [
  {
    id: "session-mon-exam-review",
    courseCode: "CS101",
    courseName: "Introduction to Computer Science",
    calendarLabel: "CS101",
    title: "Exam Review",
    topic: "Midterm review and study strategies",
    day: "mon",
    dateLabel: "Mon, Oct 23",
    startTime: "10:00 AM",
    endTime: "11:30 AM",
    startHour: 10,
    endHour: 11.5,
    location: "Room 402",
    mode: "in-person",
    accent: "navy-yellow",
  },
  {
    id: "session-tue-lab",
    courseCode: "CS202",
    courseName: "Systems Programming",
    calendarLabel: "CS202",
    title: "Lab",
    topic: "Systems Architecture lab support",
    day: "tue",
    dateLabel: "Tue, Oct 24",
    startTime: "09:00 AM",
    endTime: "10:00 AM",
    startHour: 9,
    endHour: 10,
    location: "Lab Studio B",
    mode: "in-person",
    accent: "navy-red",
  },
  {
    id: "session-wed-kernel-projects",
    courseCode: "CS305",
    courseName: "Operating Systems",
    calendarLabel: "CS305",
    title: "Kernel Projects",
    topic: "Kernel Synchronization",
    day: "wed",
    dateLabel: "Today",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    startHour: 14,
    endHour: 16,
    location: "Virtual: Zoom Link A",
    mode: "online",
    accent: "yellow",
    hasWarning: true,
    hasLocationOverride: true,
    overrideLocation: "Virtual: Zoom Link A",
  },
  {
    id: "session-thu-dropin",
    courseCode: "CS101",
    courseName: "Introduction to Computer Science",
    calendarLabel: "CS101",
    title: "Drop-in",
    topic: "Weekly Drop-in",
    day: "thu",
    dateLabel: "Thu, Oct 26",
    startTime: "09:00 AM",
    endTime: "10:30 AM",
    startHour: 9,
    endHour: 10.5,
    location: "Room 402",
    mode: "in-person",
    accent: "navy-yellow",
  },
  {
    id: "session-fri-support",
    courseCode: "TA Hours",
    courseName: "Teaching Assistant Office Hours",
    calendarLabel: "TA Hours",
    title: "General",
    topic: "General Support",
    day: "fri",
    dateLabel: "Fri, Oct 27",
    startTime: "10:30 AM",
    endTime: "11:30 AM",
    startHour: 10.5,
    endHour: 11.5,
    location: "Support Hub",
    mode: "hybrid",
    accent: "navy-red",
  },
];

export const DEFAULT_SELECTED_SESSION_ID = "session-wed-kernel-projects";

export const DUMMY_ON_DUTY_TAS: OnDutyTA[] = [
  {
    id: "ta-alex-rivers",
    name: "Alex Rivers",
    statusLabel: "CS305 - OS",
    status: "active",
  },
  {
    id: "ta-sarah-chen",
    name: "Sarah Chen",
    statusLabel: "Taking a break",
    status: "break",
  },
];

export const DUMMY_RECURRING_RULES: RecurringRule[] = [
  {
    id: "recurring-cs101",
    courseCode: "CS101",
    title: "Fundamental Concepts",
    repeats: "Mon, Thu",
    defaultTime: "10:00 AM - 12:00 PM",
    defaultLocation: "Engineering Hall, Room 402",
    mode: "in-person",
    accent: "navy",
  },
  {
    id: "recurring-cs202",
    courseCode: "CS202",
    title: "Systems Architecture",
    repeats: "Tue",
    defaultTime: "09:00 AM - 11:00 AM",
    defaultLocation: "Online (Zoom)",
    mode: "online",
    accent: "red",
  },
  {
    id: "recurring-cs305",
    courseCode: "CS305",
    title: "Operating Systems",
    repeats: "Wed, Fri",
    defaultTime: "02:00 PM - 04:00 PM",
    defaultLocation: "Hybrid Mode",
    mode: "hybrid",
    accent: "gold",
  },
];
