import { buildCalendarTimeSlots } from "@/lib/scheduling/time";
import type {
  CalendarDay,
  RecurringRule,
  ScheduleSession,
  TimeSlot,
} from "./types";

// Static calendar grid config. Live sessions/rules load via scheduling server actions.
export const CALENDAR_DAYS: CalendarDay[] = [
  { key: "mon", label: "MON", date: "23" },
  { key: "tue", label: "TUE", date: "24" },
  { key: "wed", label: "WED", date: "25" },
  { key: "thu", label: "THU", date: "26" },
  { key: "fri", label: "FRI", date: "27" },
];

export const TIME_SLOTS: TimeSlot[] = buildCalendarTimeSlots();

export const DUMMY_SCHEDULE_SESSIONS: ScheduleSession[] = [
  {
    id: "session-mon-exam-review",
    courseCode: "CS101",
    courseName: "Introduction to Computer Science",
    sessionTypeLabel: "Drop-in",
    calendarLabel: "Drop-in",
    title: "Exam Review",
    topic: "Midterm review and study strategies",
    day: "mon",
    dateLabel: "Mon, Oct 23",
    startTime: "10:00 AM",
    endTime: "11:30 AM",
    startHour: 10,
    endHour: 11.5,
    location: "Room 402",
    mode: "in-person",
    accent: "navy-yellow",
  },
  {
    id: "session-tue-lab",
    courseCode: "CS202",
    courseName: "Systems Programming",
    sessionTypeLabel: "Topic Group",
    calendarLabel: "Topic Group",
    title: "Lab",
    topic: "Systems Architecture lab support",
    day: "tue",
    dateLabel: "Tue, Oct 24",
    startTime: "09:00 AM",
    endTime: "10:00 AM",
    startHour: 9,
    endHour: 10,
    location: "Lab Studio B",
    mode: "in-person",
    accent: "navy-red",
  },
  {
    id: "session-wed-kernel-projects",
    courseCode: "CS305",
    courseName: "Operating Systems",
    sessionTypeLabel: "Debugging Queue",
    calendarLabel: "Debugging Queue",
    title: "Kernel Projects",
    topic: "Kernel Synchronization",
    day: "wed",
    dateLabel: "Today",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    startHour: 14,
    endHour: 16,
    location: "Virtual: Zoom Link A",
    mode: "online",
    accent: "yellow",
    hasOverride: true,
    overrideLocation: "Virtual: Zoom Link A",
  },
  {
    id: "session-thu-dropin",
    courseCode: "CS101",
    courseName: "Introduction to Computer Science",
    sessionTypeLabel: "Drop-in",
    calendarLabel: "Drop-in",
    title: "Drop-in",
    topic: "Weekly Drop-in",
    day: "thu",
    dateLabel: "Thu, Oct 26",
    startTime: "09:00 AM",
    endTime: "10:30 AM",
    startHour: 9,
    endHour: 10.5,
    location: "Room 402",
    mode: "in-person",
    accent: "navy-yellow",
  },
  {
    id: "session-fri-support",
    courseCode: "TA Hours",
    courseName: "Teaching Assistant Office Hours",
    sessionTypeLabel: "Topic Group",
    calendarLabel: "Topic Group",
    title: "General",
    topic: "General Support",
    day: "fri",
    dateLabel: "Fri, Oct 27",
    startTime: "10:30 AM",
    endTime: "11:30 AM",
    startHour: 10.5,
    endHour: 11.5,
    location: "Support Hub",
    mode: "hybrid",
    accent: "navy-red",
  },
];

export const DEFAULT_SELECTED_SESSION_ID = "session-wed-kernel-projects";

export const DUMMY_RECURRING_RULES: RecurringRule[] = [
  {
    id: "recurring-cs101",
    courseCode: "CS101",
    sessionTypeLabel: "Drop-in",
    title: "Fundamental Concepts",
    repeats: "Mon, Thu",
    validFrom: "Jan 6, 2026",
    validUntil: "Apr 30, 2026",
    defaultTime: "10:00 AM - 12:00 PM",
    startTime: "10:00",
    endTime: "12:00",
    defaultLocation: "Engineering Hall, Room 402",
    mode: "in-person",
    accent: "navy",
  },
  {
    id: "recurring-cs202",
    courseCode: "CS202",
    sessionTypeLabel: "Topic Group",
    title: "Systems Architecture",
    repeats: "Tue",
    validFrom: "Jan 6, 2026",
    validUntil: "Apr 30, 2026",
    defaultTime: "09:00 AM - 11:00 AM",
    startTime: "09:00",
    endTime: "11:00",
    defaultLocation: "Online (Zoom)",
    mode: "online",
    accent: "red",
  },
  {
    id: "recurring-cs305",
    courseCode: "CS305",
    sessionTypeLabel: "Debugging Queue",
    title: "Operating Systems",
    repeats: "Wed, Fri",
    validFrom: "Jan 6, 2026",
    validUntil: "Apr 30, 2026",
    defaultTime: "02:00 PM - 04:00 PM",
    startTime: "14:00",
    endTime: "16:00",
    defaultLocation: "Hybrid Mode",
    mode: "hybrid",
    accent: "gold",
  },
];
