import { CalendarPlus, Clock3, MapPin, PlusCircle, Users } from "lucide-react";
import type { OneTimeSessionListItem } from "./types";

interface OneTimeSessionsProps {
  sessions: OneTimeSessionListItem[];
  canEdit?: boolean;
  onCreateSession?: () => void;
  onSelectSession?: (sessionId: string) => void;
}

export function OneTimeSessions({
  sessions,
  canEdit = false,
  onCreateSession,
  onSelectSession,
}: OneTimeSessionsProps) {
  return (
    <section className="space-y-5">
      <div className="max-w-3xl">
        <h2 className="text-2xl font-semibold text-[#071f41]">
          One-time Sessions
        </h2>
        <p className="mt-2 text-sm leading-6 text-slate-600">
          Standalone office hours that are not generated by a recurring rule.
          Select a session here or on the calendar to edit it.
        </p>
      </div>

      {sessions.length === 0 ? (
        <div className="rounded-[28px] border border-dashed border-slate-300 bg-white px-6 py-10 text-center shadow-[0_18px_50px_-30px_rgba(15,41,66,0.2)]">
          <p className="text-sm leading-6 text-slate-600">
            No one-time sessions yet.
          </p>
          {canEdit && onCreateSession ? (
            <button
              type="button"
              onClick={onCreateSession}
              className="mt-5 inline-flex items-center justify-center gap-2 rounded-full bg-[#071f41] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#0f2942]"
            >
              <PlusCircle className="h-4 w-4" />
              Add One-time Session
            </button>
          ) : null}
        </div>
      ) : (
        <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
          {sessions.map((session) => (
            <article
              key={session.id}
              className="rounded-[28px] border border-slate-200/80 bg-white p-5 shadow-[0_18px_50px_-30px_rgba(15,41,66,0.35)]"
            >
              <div className="flex items-start justify-between gap-3">
                <span className="inline-flex rounded-full bg-[#eaf1ff] px-3 py-1 text-xs font-semibold text-[#071f41]">
                  {session.sessionTypeLabel}
                </span>
                <span className="text-xs font-medium uppercase tracking-wide text-slate-400">
                  {session.status}
                </span>
              </div>

              <h3 className="mt-4 text-lg font-semibold text-[#071f41]">
                {session.title}
              </h3>

              <div className="mt-4 space-y-3 text-sm text-slate-600">
                <p className="flex items-center gap-2">
                  <CalendarPlus className="h-4 w-4 shrink-0 text-slate-400" />
                  <span>{session.dateLabel}</span>
                </p>
                <p className="flex items-center gap-2">
                  <Clock3 className="h-4 w-4 shrink-0 text-slate-400" />
                  <span>{session.timeLabel}</span>
                </p>
                <p className="flex items-center gap-2">
                  <MapPin className="h-4 w-4 shrink-0 text-slate-400" />
                  <span>{session.location}</span>
                </p>
                <p className="flex items-center gap-2">
                  <Users className="h-4 w-4 shrink-0 text-slate-400" />
                  <span>{session.hostLabel}</span>
                </p>
              </div>

              {onSelectSession ? (
                <button
                  type="button"
                  onClick={() => onSelectSession(session.id)}
                  className="mt-5 inline-flex items-center justify-center rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold text-[#071f41] transition hover:bg-slate-50"
                >
                  View / edit
                </button>
              ) : null}
            </article>
          ))}
        </div>
      )}
    </section>
  );
}
